name: npm-publish
on:
  release:
    types: [created]
jobs:
  release:
    name: npm-publish
    runs-on: ubuntu-18.04
    steps:
      - name: CheckoutÀù
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ALKAMIN_PAT }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          scope: "alkamin"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm ci
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.ALKAMIN_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
